### ISSUE TITLE
Auto mode - not needed!!!

### ISSUE THREAD

**Issue by Aliskin-Papa** [voed/esphome_prana_ble#10]
Realy, auto mode Recuperator in the HA - not needed!!!
Because he is inadequate.
Just make two fans, separately - external and internal, without any modes.
In the HA, having data from the TVOC and CO2 sensors (not necessarily from the recuperator), everyone will be able to control the operation of the internal and external fans.

**Comment by voed** [comment]
Hi. I know that auto mode switch is currently broken for devices with auto+ mode, check #5 for details or just remove the switch from your config.
Currently i don't have a time to implement separate fan control, i will try to do that in a few weeks.
