### ISSUE TITLE
Outside Temperature

### ISSUE THREAD

**Issue by vpritulin** [voed/esphome_prana_ble#12]
Prana 200c eco life no information about outside temperature at the outlet. In homeassistant it is displayed 0
![image](https://github.com/user-attachments/assets/f2c7afc5-1ea4-4c85-8df5-d3da04fd5180)

**Comment by vpritulin** [comment]
Also on the screenshot you can see that the voltage and frequency are 0, but this isn't so important for me

**Comment by voed** [comment]
Hi. Voltage and frequency are only available for some old models so you can just remove them from the config.
For a temperature please change log level to verbose and provide packet log(as described [here](https://github.com/voed/esphome_prana_ble/issues/5#issuecomment-2317623861))

**Comment by vpritulin** [comment]
@voed My log file
[logs_prana-rec_logs.txt](https://github.com/user-attachments/files/17421918/logs_prana-rec_logs.txt)

**Comment by vpritulin** [comment]
I look in the application, there are only 3 temperatures, so I think this is normal for this model. Maybe on other versions the recuperator has 4 of them
![telegram-cloud-photo-size-2-5228721769614009638-y](https://github.com/user-attachments/assets/7b88f1b5-740d-48ea-8769-3eab43fb6b85)

**Comment by voed** [comment]
I see. Yes, according to logs your device has only one outside sensor. Just remove it from the config then.
