### ISSUE TITLE
missing "night" and "boost" mode

### ISSUE THREAD

**Issue by mario-tux** [voed/esphome_prana_ble#23]
In my units I got two extra modes: "night" and "boost" mode. It looks in an exclusive mode with manual, auto and auto+ modes so we could add them to such list in the fan modes. Do you have enough information from the reverse engineering of the bluetooth protocol to support command launch and gathering feedback information or you you need extra packages capture?

**Comment by voed** [comment]
This modes just changes fan speed to min and max, so i don't see much reason to implement that. But if you find them useful i can add them of course.

**Comment by mario-tux** [comment]
I understand your point but it would be just to clone the app functionalities in the component. One is then free to enable and use such controls. 

My 2 cents.

**Comment by voed** [comment]
At least on my device it's just a buttons to change fan speed, so i can impelent it as buttons.

**Comment by mario-tux** [comment]
The logic is similar to the fan modes: manual, auto, auto+, night or boost.

**Comment by voed** [comment]
I mean there is no any way to track that "boost" or "night" state, so if i make that it will conflict: when in auto mode and fan speed is 1 it will show night mode instead.

**Comment by mario-tux** [comment]
Ok. I think you can ignore this request. It is not very useful.
