### ISSUE TITLE
[OT] donation channel

### ISSUE THREAD

**Issue by mario-tux** [voed/esphome_prana_ble#24]
I've tried to make a donation to the project using the provided Monobank link. The payment fails trying to use Google Pay method (the only I use among the suggested ones). Could you add some other way to send you donations (Paypal or others)?

Thanks for your efforts.

**Comment by voed** [comment]
Try this link, not sure if it will work
https://www.paypal.com/donate/?hosted_button_id=84J2NHXU5EF7L

**Comment by mario-tux** [comment]
It didn't work again...
![Screenshot From 2024-11-08 20-52-53](https://github.com/user-attachments/assets/b77e0fa7-9512-4796-bc2b-6453ab20dc35)
![image](https://github.com/user-attachments/assets/6004d2e8-1b7d-4cea-9a47-d876ff861e54)

**Comment by voed** [comment]
Maybe try by email `voed@i.ua`, it should work. We have some limitations on paypal payments.

**Comment by mario-tux** [comment]
Ok, I managed to send as gift to the last email. It worked.

Consider to insert other references in the README.

**Comment by voed** [comment]
Thanks!
