### ISSUE TITLE
Add switches for Air Supply and Air Extraction 

### ISSUE THREAD

**Issue by okruts** [voed/esphome_prana_ble#7]
As per previous discovery we have specific commands to disable Air Supply / Air Extraction.

It can be useful to turn off Air Supply for example when Air Quality outside is bad. I don't know why prana is not implemented this as my recuperator is often goes in a loop (in auto mode) when air outside is bad and recuperator is intaking air and immediately trying to extract it on max fan speed as it has only one inside VOC sensor 

ble commands:
`beef040d` - turn off/on air supply 
`beef0410` - turn off/on air extraction

**Comment by voed** [comment]
It is planned to implement separate controls for intake/extract fans, but for now i don't know how to make that without confusing what is actually controlled. It may be done only by adding two more fan entities, so there will be one fan to control both fans, one fan to control intake fan, one fan to control extract fan and a switch entity to switch between separate controlling. And looks like there are no way to mark fan unavailable so all 3 of them will be active all the time.
But if it's really necessary for you, i can implement the switches for now.

**Comment by matlar83** [comment]
I want, first of all, to say thank you for this amazing project! I'm currently testing it with success with Prana ERP 160 and Prana ERP 210.

For this specific topic,
I suggest to have just two fans (intake/extract) + 1 switch to lock the two fans speed.
If the switch is off, the two fans are independent, if it is on instead, the two fans are locked and changes to one fan speed result in the same speed applied also to the other one.
Does it make sense to you?

**Comment by voed** [comment]
I will think about it, thanks
